.PHONY: help letloop argon2 blake3 sodium oprf opaque liburing check cmark shaders font-bundle


SCHEME=$(shell which scheme)
PWD=$(shell pwd)
LETLOOP=$(shell which letloop)
SHELL=/bin/bash
PREFIX=$(PWD)/local

help: ## Help!...
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

./local/bin/scheme: chezscheme

chezscheme: ## Compile latest chezscheme
	rm -rf $(PREFIX)/src/chezscheme
	mkdir -p $(PREFIX)/src
	cd $(PREFIX)/src && git clone https://github.com/cisco/chezscheme
	cd $(PREFIX)/src/chezscheme && git checkout main
	cd $(PREFIX)/src/chezscheme && ./configure --threads --disable-x11 --disable-curses --kernelobj --installprefix=$(PREFIX)/
	cd $(PREFIX)/src/chezscheme && make -j$(shell nproc --ignore 1)
	cd $(PREFIX)/src/chezscheme && make install

letloop: clean src/letloop-program.c src/letloop-usage.md src/letloop/base.scm ## Produce a.out from letloop/base.scm's procedure called letloop-main
	echo $(SCHEME)
	$(SCHEME) --version
	echo '(generate-wpo-files #t)(import (letloop base)) (letloop-compile (list "./src/" "src/letloop/base.scm" "letloop-main"))' | $(SCHEME) --quiet --libdirs ./src/ --compile-imported-libraries
	cp a.out $(PREFIX)/bin/letloop
	@echo What is done is not to be done!

font-bundle: ## Regenerate font-bundled.scm from FullCyrAsia-DejaVu30x16.psf.gz (PSF2, ~32K, ASCII coverage)
	@command -v gunzip >/dev/null || { echo "gunzip required"; exit 1; }
	@FONT=/usr/share/consolefonts/FullCyrAsia-DejaVu30x16.psf.gz; \
	  test -e "$$FONT" || { echo "$$FONT not found — install console-setup-linux"; exit 1; }; \
	  gunzip -c "$$FONT" > /tmp/letloop-bundled.psf
	python3 scripts/psf-to-scheme.py /tmp/letloop-bundled.psf bundled-psf2 \
	  > src/letloop/desktop/font-bundled.scm
	@echo "Regenerated src/letloop/desktop/font-bundled.scm"

shaders: ## Recompile desktop SPIR-V from GLSL into shader.scm (needs glslangValidator)
	@command -v glslangValidator >/dev/null || { \
	  echo "glslangValidator not found — install glslang-tools or download from https://github.com/KhronosGroup/glslang/releases"; \
	  exit 1; \
	}
	glslangValidator -V src/letloop/desktop/shaders/text.vert -o /tmp/text.vert.spv
	glslangValidator -V src/letloop/desktop/shaders/text.frag -o /tmp/text.frag.spv
	@printf '%s\n' \
	  ';; SPIR-V bytecode for the text-rendering pipeline.' \
	  ';;' \
	  ';; Generated by `make shaders` from src/letloop/desktop/shaders/' \
	  ';; {text.vert,text.frag}. The bytevectors are checked in so a clean' \
	  ';; build does not need a SPIR-V compiler.' \
	  '(library (letloop desktop shader)' \
	  '  (export text-vertex-spirv text-fragment-spirv)' \
	  '  (import (chezscheme))' \
	  '' > src/letloop/desktop/shader.scm
	python3 scripts/spv-to-scheme.py /tmp/text.vert.spv text-vertex-spirv >> src/letloop/desktop/shader.scm
	python3 scripts/spv-to-scheme.py /tmp/text.frag.spv text-fragment-spirv >> src/letloop/desktop/shader.scm
	@echo ')' >> src/letloop/desktop/shader.scm
	@echo "Regenerated src/letloop/desktop/shader.scm"

todo: ## So say we all!
	@grep -nR --color=always -B 2 -A 2 TODO src/

xxx: ## For those born under the eye of a wandering star...
	@grep -nR --color=always -B 2 -A 2 XXX src/


liburing:  ## Build liburing from source
	rm -rf $(PREFIX)/src/liburing
	mkdir -p $(PREFIX)/src
	cd $(PREFIX)/src && git clone https://github.com/axboe/liburing
	cd $(PREFIX)/src/liburing && git checkout liburing-2.14
	cd $(PREFIX)/src/liburing && ./configure --prefix=$(PREFIX)/
	cd $(PREFIX)/src/liburing && make -j$(shell nproc --ignore 1)
	cd $(PREFIX)/src/liburing && make liburing.pc
	cd $(PREFIX)/src/liburing && make install

argon2: ## Build libargon2 from source
	rm -rf $(PREFIX)/src/argon2
	mkdir -p $(PREFIX)/src
	cd $(PREFIX)/src && git clone https://github.com/P-H-C/phc-winner-argon2 argon2
	cd $(PREFIX)/src/argon2 && git checkout 20190702
	cd $(PREFIX)/src/argon2 && make -j$(shell nproc --ignore 1)
	cp $(PREFIX)/src/argon2/libargon2.so.1 $(PREFIX)/lib/
	cp $(PREFIX)/src/argon2/libargon2.a $(PREFIX)/lib/

blake3: ## Build libblake3 from source
	rm -rf $(PREFIX)/src/blake3
	mkdir -p $(PREFIX)/src
	cd $(PREFIX)/src && git clone https://github.com/BLAKE3-team/BLAKE3 blake3
	cd $(PREFIX)/src/blake3 && git checkout 1.8.3
	cd $(PREFIX)/src/blake3/c && gcc -shared -O3 -o libblake3.so -fPIC blake3.c blake3_dispatch.c blake3_portable.c blake3_sse2_x86-64_unix.S blake3_sse41_x86-64_unix.S blake3_avx2_x86-64_unix.S blake3_avx512_x86-64_unix.S
	cd $(PREFIX)/src/blake3/c && gcc -c -O3 -fPIC blake3.c blake3_dispatch.c blake3_portable.c blake3_sse2_x86-64_unix.S blake3_sse41_x86-64_unix.S blake3_avx2_x86-64_unix.S blake3_avx512_x86-64_unix.S && ar rcs libblake3.a blake3.o blake3_dispatch.o blake3_portable.o blake3_sse2_x86-64_unix.o blake3_sse41_x86-64_unix.o blake3_avx2_x86-64_unix.o blake3_avx512_x86-64_unix.o
	cp $(PREFIX)/src/blake3/c/libblake3.so $(PREFIX)/lib/
	cp $(PREFIX)/src/blake3/c/libblake3.a $(PREFIX)/lib/

picohttpparser: ## Build libpicohttpparser from source
	rm -rf $(PWD)/local/src/picohttpparser
	mkdir -p $(PWD)/local/src $(PWD)/local/lib
	cd $(PWD)/local/src && git clone https://github.com/h2o/picohttpparser
	cp $(PWD)/src/letloop/picohttpparser_wrapper.c $(PWD)/local/src/picohttpparser/
	cd $(PWD)/local/src/picohttpparser && gcc -shared -O3 -o libpicohttpparser.so -fPIC picohttpparser_wrapper.c
	cd $(PWD)/local/src/picohttpparser && gcc -c -O3 -fPIC picohttpparser_wrapper.c && ar rcs libpicohttpparser.a picohttpparser_wrapper.o
	cp $(PWD)/local/src/picohttpparser/libpicohttpparser.so $(PWD)/local/lib/
	cp $(PWD)/local/src/picohttpparser/libpicohttpparser.a $(PWD)/local/lib/

sodium: ## Build libsodium from source
	rm -rf $(PREFIX)/src/libsodium
	mkdir -p $(PREFIX)/src
	cd $(PREFIX)/src && git clone --branch 1.0.21-RELEASE https://github.com/jedisct1/libsodium
	cd $(PREFIX)/src/libsodium && ./configure --prefix=$(PREFIX)
	cd $(PREFIX)/src/libsodium && make -j$(shell nproc --ignore 1)
	cd $(PREFIX)/src/libsodium && make install

oprf: sodium ## Build liboprf from source
	rm -rf $(PREFIX)/src/liboprf
	mkdir -p $(PREFIX)/src
	cd $(PREFIX)/src && git clone --branch v0.9.4 https://github.com/stef/liboprf
	cd $(PREFIX)/src/liboprf/src && make -C noise_xk all CFLAGS="-Wall -O2 -g -fpic -I$(PREFIX)/include" LDFLAGS="-L$(PREFIX)/lib"
	cd $(PREFIX)/src/liboprf/src && $(CC) -Wall -O2 -g -fpic -DHAVE_SODIUM_HKDF=1 -I$(PREFIX)/include -Inoise_xk/include -Inoise_xk/include/karmel -Inoise_xk/include/karmel/minimal -c oprf.c toprf.c dkg.c dkg-vss.c utils.c tp-dkg.c mpmult.c stp-dkg.c toprf-update.c
	cd $(PREFIX)/src/liboprf/src && $(LD) -r -o liboprf_merged.o oprf.o toprf.o dkg.o dkg-vss.o utils.o tp-dkg.o mpmult.o stp-dkg.o toprf-update.o
	cd $(PREFIX)/src/liboprf/src && $(CC) -Wall -O2 -g -fpic -shared -Wl,-soname,liboprf.so.0 -o liboprf.so liboprf_merged.o -L$(PREFIX)/lib -lsodium -loprf-noiseXK -Lnoise_xk
	cd $(PREFIX)/src/liboprf/src && ar rcs liboprf.a oprf.o toprf.o dkg.o dkg-vss.o utils.o tp-dkg.o mpmult.o stp-dkg.o toprf-update.o
	mkdir -p $(PREFIX)/lib $(PREFIX)/include/oprf
	cp $(PREFIX)/src/liboprf/src/liboprf.so $(PREFIX)/lib/
	cp $(PREFIX)/src/liboprf/src/liboprf.a $(PREFIX)/lib/
	cp $(PREFIX)/src/liboprf/src/noise_xk/liboprf-noiseXK.so $(PREFIX)/lib/
	cp $(PREFIX)/src/liboprf/src/noise_xk/liboprf-noiseXK.a $(PREFIX)/lib/
	cp $(PREFIX)/src/liboprf/src/oprf.h $(PREFIX)/include/oprf/
	cp $(PREFIX)/src/liboprf/src/toprf.h $(PREFIX)/include/oprf/
	cp $(PREFIX)/src/liboprf/src/toprf-update.h $(PREFIX)/include/oprf/
	cp $(PREFIX)/src/liboprf/src/dkg.h $(PREFIX)/include/oprf/
	cp $(PREFIX)/src/liboprf/src/tp-dkg.h $(PREFIX)/include/oprf/
	cp $(PREFIX)/src/liboprf/src/stp-dkg.h $(PREFIX)/include/oprf/
	cp $(PREFIX)/src/liboprf/src/utils.h $(PREFIX)/include/oprf/

cmark: ## Build libcmark from source
	rm -rf $(PWD)/local/src/cmark
	mkdir -p $(PWD)/local/src
	cd $(PWD)/local/src && git clone --branch 0.31.2 https://github.com/commonmark/cmark
	cd $(PWD)/local/src/cmark && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$(PWD)/local/ .. && make -j$(shell nproc --ignore 1) && make install

opaque: oprf ## Build libopaque from source
	rm -rf $(PREFIX)/src/libopaque
	mkdir -p $(PREFIX)/src
	cd $(PREFIX)/src && git clone https://github.com/stef/libopaque && cd libopaque && git checkout 98f6a6e
	cd $(PREFIX)/src/libopaque/src && make -j$(shell nproc --ignore 1) libopaque.so libopaque.a PREFIX=$(PREFIX) OPRFINCDIR=$(PREFIX)/include SODIUM_NEWER_THAN_1_0_18=0 CFLAGS="-Wall -O2 -g -fpic -I$(PREFIX)/include -DHAVE_SODIUM_HKDF=1" LDFLAGS="-L$(PREFIX)/lib -lsodium -loprf"
	cp $(PREFIX)/src/libopaque/src/libopaque.so $(PREFIX)/lib/
	cp $(PREFIX)/src/libopaque/src/libopaque.a $(PREFIX)/lib/

check: letloop-check.sh clean ## Hit the ground running!
	LD_LIBRARY_PATH=$(PREFIX)/lib/ echo '(import (letloop base)) (letloop-check (list "./src/"))' | $(SCHEME) --quiet --libdirs ./src/
	SCHEME=$(SCHEME) LD_LIBRARY_PATH=$(PREFIX)/lib/ LETLOOP=$(LETLOOP) sh letloop-check.sh
	LETLOOP=$(LETLOOP) bash checks/letloop/srp.sh

stress: clean ## check stress implementations
	sh checks/stress-transparenturing.sh

check-fail-fast: letloop-check.sh clean ## Hit the ground running!
	LD_LIBRARY_PATH=$(PREFIX)/lib/ echo '(import (letloop base)) (letloop-check (list "./src/" "--fail-fast"))' | $(SCHEME) --quiet --libdirs ./src/
	SCHEME=$(SCHEME) LD_LIBRARY_PATH=$(PREFIX)/lib/ LETLOOP=$(LETLOOP) sh letloop-check.sh
	LETLOOP=$(LETLOOP) bash checks/letloop/srp.sh
	LETLOOP=$(LETLOOP) sh checks/stress-transparenturing.sh

clean:
	$(shell find src/ -name "*.so" | xargs rm -f)
	$(shell find src/ -name "*.wpo" | xargs rm -f)
	$(shell find examples/ -name "*.so" | xargs rm -f)
	$(shell find examples/ -name "*.wpo" | xargs rm -f)
	$(shell find benchmarks/ -name "*.so" | xargs rm -f)
	$(shell find benchmarks/ -name "*.wpo" | xargs rm -f)
	rm -rf /tmp/letloop/
