#!/usr/bin/env bash

if [ ! "$LETLOOP_VENV" ]; then
    export LETLOOP_ROOT=$(pwd)
    export LETLOOP_VENV=yes
    if [ "x$1" != "x" ]; then
        export LETLOOP_PREFIX=$1
        shift
    else
        export LETLOOP_PREFIX=$(pwd)/local
    fi
    mkdir -p "$LETLOOP_PREFIX/bin"
    export SCHEME=$LETLOOP_ROOT/local/bin/scheme
    export LD_LIBRARY_PATH="$LETLOOP_PREFIX/lib/"
    export PATH="$LETLOOP_PREFIX/bin:$HOME/.local/bin:$PATH"
    if [ $# -eq 0 ]; then
        echo "Entering letloop... There is $(make todo | grep TODO | wc -l) TODOs..."
        $SHELL
    else
        exec $@
    fi
else
    echo "You are already in letloop!"
fi
