#!/usr/bin/env python3
"""Emit a Scheme library that exports a bundled PSF font as a bytevector.

Usage:
    psf-to-scheme.py <path/to/font.psf> <library-export-name>

Writes to stdout. The output is a complete `#!chezscheme` library
under `(letloop desktop font-bundled)` that defines the named
identifier as a bytevector with the file contents.
"""
import os
import sys


HEADER = """\
;; Bundled console font for the M2.2 text-rendering deliverable.
;;
;; Generated by `make font-bundle` (which runs scripts/psf-to-scheme.py)
;; from a system PSF2 font. Bytevector is checked in so a fresh clone
;; can build letloop without external font files.
;;
;; Source: {source}
(library (letloop desktop font-bundled)
  (export {ident})
  (import (chezscheme))
"""


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: psf-to-scheme.py PATH IDENT\n")
        sys.exit(2)
    path, ident = sys.argv[1], sys.argv[2]
    with open(path, "rb") as f:
        data = f.read()
    sys.stdout.write(HEADER.format(source=os.path.basename(path), ident=ident))
    print(f"  ;; {len(data)} bytes")
    print(f"  (define {ident}")
    print("    (bytevector")
    chunk = []
    for b in data:
        chunk.append(f"#x{b:02x}")
        if len(chunk) == 16:
            print("     " + " ".join(chunk))
            chunk = []
    if chunk:
        print("     " + " ".join(chunk))
    print("    )))")


if __name__ == "__main__":
    main()
