name: Check

on:
  push:
    branches: [hello-schemer, dev]
  pull_request:
    branches: [hello-schemer, dev]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install -y uuid-dev libtls-dev liburing-dev wrk

      - name: Cache local
        id: cache-local
        uses: actions/cache@v4
        with:
          path: local/
          key: local-v3-${{ runner.os }}-${{ runner.arch }}

      - name: Build ChezScheme
        if: steps.cache-local.outputs.cache-hit != 'true'
        run: ./venv $(pwd)/local/ make chezscheme

      - name: Build letloop
        run: ./venv $(pwd)/local/ make letloop

      - name: Run tests
        run: ./venv $(pwd)/local/ make check-fail-fast

      - name: Run integration tests
        run: ./venv $(pwd)/local/ make check-integration
