name: Check

on:
  push:
    branches: [hello-schemer, dev]
  pull_request:
    branches: [hello-schemer, dev]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install -y uuid-dev libtls-dev liburing-dev wrk python3-srp

      - name: Cache local
        id: cache-local
        uses: actions/cache@v4
        with:
          path: local/
          key: local-v3-${{ runner.os }}-${{ runner.arch }}

      - name: Build ChezScheme
        if: steps.cache-local.outputs.cache-hit != 'true'
        run: ./venv $(pwd)/local/ make chezscheme

      - name: Build C dependencies
        if: steps.cache-local.outputs.cache-hit != 'true'
        run: ./venv $(pwd)/local/ make opaque argon2 blake3 liburing

      - name: Build letloop
        run: ./venv $(pwd)/local/ make letloop

      - name: Run tests
        run: ./venv $(pwd)/local/ make check-fail-fast
