name: Continuous Integration

on:
    push:

jobs:
  checks:
    runs-on: ubuntu-22.04
    name: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: sudo apt install chezscheme chezscheme-dev uuid-dev liblz4-dev
      - run: scheme --program letloop.scm compile /usr/lib/csv9.5.4/ta6le/ letloop.scm letloop
      - run: letloop exec example.scm
      - run: |
          letloop compile /usr/lib/csv9.5.4/ta6le/ example.scm example
          ./example
      - run: letloop check tests/check-success.scm
